version: '3'

services:
  postgres:
    container_name: 'file_uploader_postgres'
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-processor}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: 'file_uploader_redis'
    command: redis-server
    volumes:
      - file_uploader:/data

  web:
    build: .
    restart: unless-stopped
    container_name: 'file_uploader_django'
    command: gunicorn file_uploader.wsgi:application -b 0.0.0.0:8000
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
    volumes:
      - ./file_uploader/:/app

  celery:
    build: .
    restart: unless-stopped
    container_name: 'file_uploader_celery'
    command: celery -A file_uploader worker -l INFO
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - web
      - redis
    volumes:
      - ./file_uploader/:/app

  flower:
    image: mher/flower
    command: celery --broker=redis://redis:6379 flower
    ports:
      - '5555:5555'
    depends_on:
      - redis

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - '80:8000'
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./file_uploader/static:/www/static
      - ./file_uploader/media:/www/media
    depends_on:
      - web
      - postgres

volumes:
  file_uploader:
  postgres:
